### ISSUE TITLE
Replace `osu-storyboard-parser` with `osu-parsers`

### ISSUE THREAD

**Issue by blueberrymuffin3** [blueberrymuffin3/osu-js#26]
Now that kionell [rewrote the storyboard parser in `osu-parsers`](https://github.com/kionell/osu-parsers/issues/3), I should look into effectively reverting 16ba66cf97170b69d8a39d695637b60b9bc16a2b

- [x] Blocked on kionell/osu-parsers#6

**Comment by kionell** [comment]
I'm currently working on this and i wanted to say that this replacement partially?? breaks the rendering. I believe the problem is in the way command loops are handled. `osu-parsers` and osu!lazer store commands with relative start time, while your thing removes the need for iteration by unrolling loops. Because of this `osu-js` thinks that all commands in loops have absolute time even though they don't.
