### ISSUE TITLE
Super weird bug in slider path rendering

### ISSUE THREAD

**Issue by kionell** [blueberrymuffin3/osu-js#62]
I'm currently working on something big and i can't finish it because of one bug that's bothering me. This happens with EVERY slider and at first glance is not noticeable at all. At the very beginning of the slider, when it is just starting to fade in, the path appears in the wrong place literally for 1-2 frames.

![image](https://user-images.githubusercontent.com/43014304/185978048-23e9c6d1-85b7-4854-91ad-f546d44c29dc.png)
![image](https://user-images.githubusercontent.com/43014304/185981309-28008fb3-453d-4a95-a4f9-aafee3f4e93b.png)
![image](https://user-images.githubusercontent.com/43014304/185981418-9f705430-9874-4116-b77d-bd6480cdb173.png)

And after that, the slider itself starts drawing the path, but skipping that piece, which appeared at the beginning by 1-2 frames.
![image](https://user-images.githubusercontent.com/43014304/185981908-45c6b831-4cd3-4304-a1b1-0d8ffdcbe7a8.png)

Slider path sprite with alpha locked to 1:
![image](https://user-images.githubusercontent.com/43014304/185982776-ea6e5f98-ee0f-4d66-9242-252d8b586cd1.png)

**Comment by blueberrymuffin3** [comment]
The position of the SliderPathSprite is set here:
https://github.com/blueberrymuffin3/osu-js/blob/602cbafaae93950b88655cdd4e792a89358c811d/src/play/render/standard/components/slider_path.ts#L172-L174

It appears that the texture modification is processed immediately, while the position modification is deferred until the next frame.
The transform matrices of each display object are calculated *before* the `_render` function is called, since you're not really supposed to modify anything in the render function.

I'm working on a fix RN.
